# Generated by Django 3.0.6 on 2020-06-02 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAlumnos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='estudiantes',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='maestros',
            name='codigo',
        ),
    ]
